/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DefaultHeader: typeof import('./components/layouts/DefaultHeader.vue')['default']
    DefaultLayout: typeof import('./components/layouts/DefaultLayout.vue')['default']
    DragToUpload: typeof import('./components/common/DragToUpload.vue')['default']
    DropdownLocal: typeof import('./components/layouts/DropdownLocal.vue')['default']
    DropdownUser: typeof import('./components/layouts/DropdownUser.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ListTable: typeof import('./components/common/ListTable.vue')['default']
    MobileAsideMenu: typeof import('./components/layouts/MobileAsideMenu.vue')['default']
    NavigationHeader: typeof import('./components/layouts/NavigationHeader.vue')['default']
    PageHeader: typeof import('./components/common/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
